Repository hmcts/wa-task-monitor, pull requests merged in 2022-05, with the labels that each got.

#86 RWA-1407: CVE-2016-1000027 supression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-86

#88 RWA-1428 - CVE fixes
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-88

#89 RWA-1217-avoid initiation on non-local environments
  charts/wa-task-monitor/Chart.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/MonitorTaskJobControllerForInitiationJobTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/SpringBootFunctionalBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/adhoc/MonitorTaskJobControllerForAdHocPendingTerminationTest.java
  src/functionalTest/resources/application-functional.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-89
