Repository hmcts/wa-task-monitor, pull requests merged in 2022-03, with the labels that each got.

#63 RWA-1142 add clean up helm release into PR stage
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-63

#64 refactor:Supress spring boot vunerabilities
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-64

#66 RWA-982 [SH] Upgrading springboot to 2.6.4
  build.gradle
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.properties
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/config/OpenAPIPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/SpringBootIntegrationBaseTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/config/OpenAPIConfiguration.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-66

#67 RWA-1129-migration parameters have been added into initiation and termination jobs
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/wa-task-monitor/Chart.yaml
  charts/wa-task-monitor/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerForInitiationJobTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/config/job/InitiationJobConfig.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/config/job/TerminationJobConfig.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationJobService.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/termination/TerminationJobService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationJobServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/termination/TerminationJobServiceTest.java
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-67

#73 RWA-1202 [SH] Fixing swagger doc
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-73

#75 RWA-1254 CVE-2020-36518 suppressed
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-75

#72 RWA-1237: Terminate tasks in pendingTermination state
  charts/wa-task-monitor/Chart.yaml
  charts/wa-task-monitor/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/adhoc/MonitorTaskJobControllerForAdHocPendingTerminationTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/clients/CamundaClient.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/config/job/PendingTerminationJobConfig.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/HistoryVariableInstance.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmonitor/JobName.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/pendingterminationtasks/PendingTerminationJob.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/pendingterminationtasks/PendingTerminationJobService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/pendingterminationtasks/PendingTerminationJobServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/pendingterminationtasks/PendingTerminationJobTest.java
  src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/utils/Common.java
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-72
