Repository hmcts/wa-task-monitor, pull requests merged in 2022-04, with the labels that each got.

#70 RWA-1171-add-waDummyPostcode
  src/contractTest/resources/json/case_data_map.json
  src/functionalTest/resources/requests/ccd/case_data.json
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-70

#76 RWA-1281 Suppress CVE-2022-22965 False Positive
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-76

#77 RWA-1299 Fix multiple CVE spring boot upgrade to 2.6.6
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-77

#82 RWA-1302: upgraded spring boot due to CVE-2022-22968
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-82

#78 RWA-1098-autoscaling for R1
  charts/wa-task-monitor/Chart.yaml
  charts/wa-task-monitor/values.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-78
