Repository hmcts/wa-task-monitor, pull requests merged in 2023-01, with the labels that each got.

#175 RWA-2052 Changing after callback to afterSuccess callback
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-175

#182 RWA-2057 Gradle version Update to 7.6
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-182

#185 RWA-2133 Fix CVE problem of task monitor
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-185

#177 RWA-1955-wa-task-management-api url standardized
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  charts/wa-task-monitor/Chart.yaml
  charts/wa-task-monitor/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/SpringBootFunctionalBaseTest.java
  src/functionalTest/resources/application-functional.yaml
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/clients/TaskManagementClient.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/clients/TaskReconfigurationClient.java
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-177

#149 RWA-1712: Java 17 migration
  Dockerfile
  build.gradle
  src/main/resources/application-local.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-149

#176 RWA-1993 fixed reconfiguration request time issue
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/reconfiguration/ReconfigurationJobService.java
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-176
