Repository hmcts/wa-task-monitor, pull requests merged in 2023-02, with the labels that each got.

#191 RWA-2238 Bump org.owasp.dependencycheck from 7.2.1 to 8.0.2
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-191

#193 RWA-2247 Update Helm release java to v4.0.11
  build.gradle
  charts/wa-task-monitor/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-193

#194 RWA-2248 Dependency update CVE fix for wa-task-monitor
  build.gradle
  infrastructure/.terraform-version
Labels: ns:wa, prd:wa, no-changes, rel:wa-task-monitor-pr-194

#195 RWA-2255-clean up query arranged
  charts/wa-task-monitor/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerForAdHocJobTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/clients/CamundaClient.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/HistoricCamundaTask.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/ResourceEnum.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/deleteprocessinstances/DeleteProcessInstancesJob.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/deleteprocessinstances/DeleteProcessInstancesJobService.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanup/MaintenanceCamundaTaskCleanUpJob.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanup/MaintenanceCamundaTaskCleanUpJobService.java
  src/main/resources/application.yaml
  src/main/resources/camunda/camunda-active-task-clean-up-query.json
  src/main/resources/camunda/camunda-delete-process-instances-request-parameter.json
  src/main/resources/camunda/camunda-history-task-clean-up-query.json
  src/main/resources/camunda/camunda-task-clean-up-query.json
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/DeleteProcessInstancesJobServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/DeleteProcessInstancesJobTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanup/MaintenanceCamundaTaskCleanUpJobTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanup/MaintenanceCamundaTaskMaintenanceCamundaTaskCleanUpJobServiceTest.java
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-195

#198 RWA-2324 CVE Updates
  build.gradle
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:wa, prd:wa, no-changes, rel:wa-task-monitor-pr-198
