Repository hmcts/wa-task-monitor, pull requests merged in 2023-03, with the labels that each got.

#200 RWA-2329: suppress CVE-2022-45688
  charts/wa-task-monitor/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-200

#204 RWA-2356: Gradle upgrade to 7.6.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-204

#208 Upgrade swagger version and resolve cve issue
  .github/renovate.json
  .github/workflows/swagger.yml
  Dockerfile
  build.gradle
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-208
