Repository hmcts/wa-task-monitor, pull requests merged in 2023-12, with the labels that each got.

#285 RWA-2976: Suppress CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-285

#286 RWA-2995: Fix CVE-2023-33202, CVE-2023-34055, CVE-2023-46589
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-286

#288 RWA-3004: Fix CVE-2023-6378
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-288

#291 RWA-3012 Need to upgrade OWASP - wa-task-monitor
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-291
