Repository hmcts/wa-task-monitor, pull requests merged in 2023-10, with the labels that each got.

#269 RWA-2834 Extend suppression date for CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-269

#271 RWA-2872 Upgraded Tomcat to fix new CVE's
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-271

#272 RWA-2845 Migrating to Workload Identity
  charts/wa-task-monitor/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-272

#283 RWA-2910: extend suppression for CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-283
