Repository hmcts/wa-task-monitor, pull requests merged in 2024-07, with the labels that each got.

#366 RWA-3497: Remove Suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-366

#389 Update renovate.json
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-389

#390 Renovate tuning
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-390
