Repository hmcts/wa-task-monitor, pull requests merged in 2024-10, with the labels that each got.

#435 RWA-3519-update dependencycheck version
  build.gradle
Labels: ns:wa, prd:wa, aat/no-changes, prod/no-changes, rel:wa-task-monitor-pr-435

#432 CME-33 bump java version to 21
  .github/workflows/ci.yml
  .github/workflows/publish-openapi.yml
  Dockerfile
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-432

#441 Adding app insights dependencies
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-441

#440 Rwa 3909
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerFoCleanUpJobTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerFoReconfigurationJobTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobController.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/entities/TaskOperation.java
  src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/controllers/MonitorTaskJobService.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/controllers/MonitorTaskJobServiceTest.java
Labels: ns:wa, prd:wa, aat/no-changes, prod/no-changes, rel:wa-task-monitor-pr-440
