Repository hmcts/wa-task-monitor, pull requests merged in 2024-05, with the labels that each got.

#334 RWA-3324: Extend Suppression
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-334

#344 Upgrade Terraform version.
  infrastructure/.terraform-version
Labels: ns:wa, prd:wa, aat/no-changes, prod/no-changes, rel:wa-task-monitor-pr-344

#346 RWA-3388: Extend Suppression for CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-monitor-pr-346
